apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: titanic-api-secrets
  namespace: titanic-api
  labels:
    app: titanic-api
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: titanic-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        database-url: "postgresql+psycopg2://{{ .postgresUser }}:{{ .postgresPassword }}@{{ .postgresRdsEndpoint }}:5432/{{ .postgresRdsDbname }}"
        postgres-user: "{{ .postgresUser }}"
        postgres-password: "{{ .postgresPassword }}"
        jwt-secret-key: "{{ .jwtSecretKey }}"
        postgres-rds-endpoint: "{{ .postgresRdsEndpoint }}"
        postgres-rds-dbname: "{{ .postgresRdsDbname }}"
  data:
  - secretKey: postgresUser
    remoteRef:
      key: titanic-api-prod-rds-credentials
      property: postgres-rds-dbuser
  - secretKey: postgresPassword
    remoteRef:
      key: titanic-api-prod-rds-credentials
      property: postgres-rds-password
  - secretKey: jwtSecretKey
    remoteRef:
      key: titanic-api-prod-rds-credentials
      property: jwt_secret_key
  - secretKey: postgresRdsEndpoint
    remoteRef:
      key: titanic-api-prod-rds-credentials
      property: postgres-rds-endpoint
  - secretKey: postgresRdsDbname
    remoteRef:
      key: titanic-api-prod-rds-credentials
      property: postgres-rds-dbname
