apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: titanic-api-network-policy
  namespace: titanic-api
  labels:
    app: titanic-api
spec:
  podSelector:
    matchLabels:
      app: titanic-api
      component: api
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 5000
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: titanic-api
          component: database
    ports:
    - protocol: TCP
      port: 5432
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: titanic-db-network-policy
  namespace: titanic-api
  labels:
    app: titanic-api
    component: database
spec:
  podSelector:
    matchLabels:
      app: titanic-api
      component: database
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: titanic-api
          component: api
    ports:
    - protocol: TCP
      port: 5432
  egress:
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
