apiVersion: v1
kind: Secret
metadata:
  name: titanic-secrets
  namespace: titanic-api
  labels:
    app: titanic-api
type: Opaque
stringData:
  database-url: postgresql+psycopg2://titanic_user:CHANGE_ME@titanic-db:5432/titanic_db
  postgres-user: titanic_user
  postgres-password: CHANGE_ME
  jwt-secret-key: CHANGE_ME_IN_PRODUCTION
