apiVersion: v1
kind: Service
metadata:
  name: titanic-api
  namespace: titanic-api
  labels:
    app: titanic-api
    component: api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: titanic-api
    component: api
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

---
apiVersion: v1
kind: Service
metadata:
  name: titanic-api-loadbalancer
  namespace: titanic-api
  labels:
    app: titanic-api
    component: api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: titanic-api
    component: api

---
apiVersion: v1
kind: Service
metadata:
  name: titanic-db
  namespace: titanic-api
  labels:
    app: titanic-api
    component: database
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: postgres
    protocol: TCP
    name: postgres
  selector:
    app: titanic-api
    component: database
  clusterIP: None
