apiVersion: v1
kind: Service
metadata:
  name: titanic-api
  namespace: titanic-api
  labels:
    app: titanic-api
    component: api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: titanic-api
    component: api
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

