FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libc6-dev \
    postgresql-client \
    libpq-dev \
    libpq5 \
    && rm -rf /var/lib/apt/lists/*

COPY titanic-api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY titanic-api/ /app/

ENV PYTHONUNBUFFERED=1 \
    FLASK_APP=run.py \
    FLASK_ENV=development

EXPOSE 5000

CMD ["python", "run.py"]
