apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: titanic-api
  namespace: titanic-api-prod
  labels:
    app: titanic-api
    release: prometheus
spec:
  selector:
    matchLabels:
      app: titanic-api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    scheme: http
