{{- if .Values.externalSecrets.secretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}
  labels:
    {{- include "titanic-api.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.secretStore.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.externalSecrets.secretStore.serviceAccount.name }}
            namespace: {{ .Values.externalSecrets.secretStore.serviceAccount.namespace }}
{{- end }}
