apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "titanic-api.fullname" . }}-config
  namespace: {{ .Values.namespace | default "titanic-api" }}
  labels:
    {{- include "titanic-api.labels" . | nindent 4 }}
data:
  flask-env: {{ .Values.config.flaskEnv }}
  postgres-db: {{ .Values.config.postgresDb }}
  app-name: {{ .Values.config.appName }}
  app-version: {{ .Values.config.appVersion }}
  log-level: {{ .Values.config.logLevel }}
