{{- if .Values.externalSecrets.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "titanic-api.fullname" . }}-secrets
  namespace: {{ .Values.namespace | default "titanic-api" }}
  labels:
    {{- include "titanic-api.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  refreshInterval: {{ .Values.externalSecrets.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecrets.externalSecret.targetSecretName }}
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      metadata:
        labels:
          {{- include "titanic-api.labels" . | nindent 10 }}
          app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        annotations:
          meta.helm.sh/release-name: {{ .Release.Name | quote }}
          meta.helm.sh/release-namespace: {{ .Release.Namespace | quote }}
      data:
        database-url: "postgresql+psycopg2://{{ .postgresUser }}:{{ .postgresPassword }}@{{ .postgresRdsEndpoint }}:5432/{{ .postgresRdsDbname }}"
        postgres-user: "{{ .postgresUser }}"
        postgres-password: "{{ .postgresPassword }}"
        jwt-secret-key: "{{ .jwtSecretKey }}"
        postgres-rds-endpoint: "{{ .postgresRdsEndpoint }}"
        postgres-rds-dbname: "{{ .postgresRdsDbname }}"
  data:
  - secretKey: postgresUser
    remoteRef:
      key: {{ .Values.externalSecrets.externalSecret.secretName }}
      property: postgres-rds-dbuser
  - secretKey: postgresPassword
    remoteRef:
      key: {{ .Values.externalSecrets.externalSecret.secretName }}
      property: postgres-rds-password
  - secretKey: jwtSecretKey
    remoteRef:
      key: {{ .Values.externalSecrets.externalSecret.secretName }}
      property: jwt_secret_key
  - secretKey: postgresRdsEndpoint
    remoteRef:
      key: {{ .Values.externalSecrets.externalSecret.secretName }}
      property: postgres-rds-endpoint
  - secretKey: postgresRdsDbname
    remoteRef:
      key: {{ .Values.externalSecrets.externalSecret.secretName }}
      property: postgres-rds-dbname
{{- end }}
