{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "titanic-api.fullname" . }}-pdb
  namespace: {{ .Values.namespace | default "titanic-api" }}
  labels:
    {{- include "titanic-api.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "titanic-api.selectorLabels" . | nindent 6 }}
      component: api
{{- end }}
