apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: titanic-dev

resources:
  - ../../base

replicas:
  - name: titanic-api
    count: 1

images:
  - name: titanic-api
    newName: titanic-api
    newTag: dev

patches:
  - target:
      kind: Deployment
      name: titanic-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 50m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 128Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 200m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 256Mi
  - target:
      kind: ConfigMap
      name: titanic-config
    patch: |-
      - op: replace
        path: /data/flask-env
        value: development
  - target:
      kind: HorizontalPodAutoscaler
      name: titanic-api-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3
  - target:
      kind: Ingress
      name: titanic-api-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: titanic-api-dev.example.com

configMapGenerator:
  - name: titanic-config
    behavior: merge
    literals:
      - environment=development
